// <auto-generated />
using System;
using BeatNationAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeatNationAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251024235517_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeatNationAPI.Models.Beat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Bpm")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Escala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlCapa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlMp3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlTrackout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlWav")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Beats");
                });

            modelBuilder.Entity("BeatNationAPI.Models.BeatColab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Participacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BeatId");

                    b.ToTable("BeatColabs");
                });

            modelBuilder.Entity("BeatNationAPI.Models.BeatLicencas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LicencaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BeatId");

                    b.HasIndex("LicencaId");

                    b.ToTable("BeatLicencas");
                });

            modelBuilder.Entity("BeatNationAPI.Models.Licenca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PresetLicencaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PresetLicencaId");

                    b.ToTable("Licencas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("724c5c55-ecb3-4fc1-a2ad-d77a02833d24"),
                            AtualizadoEm = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Categoria = "NaoExclusiva",
                            CriadoEm = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Licença padrão para uso básico",
                            Nome = "Básica",
                            PresetLicencaId = new Guid("97806a3e-ea4d-4c0f-a82f-664f9016990f")
                        },
                        new
                        {
                            Id = new Guid("75974e74-12de-41e4-9fca-f9b87e04e5a6"),
                            AtualizadoEm = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Categoria = "NaoExclusiva",
                            CriadoEm = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Licença avançada com mais benefícios dispóniveis",
                            Nome = "VIP",
                            PresetLicencaId = new Guid("97806a3e-ea4d-4c0f-a82f-664f9016990f")
                        },
                        new
                        {
                            Id = new Guid("ead25d1b-6568-4913-98cd-2f363f235d8b"),
                            AtualizadoEm = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Categoria = "Exclusiva",
                            CriadoEm = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Licença exclusiva para uso total e irrestrito",
                            Nome = "Exclusiva",
                            PresetLicencaId = new Guid("97806a3e-ea4d-4c0f-a82f-664f9016990f")
                        });
                });

            modelBuilder.Entity("BeatNationAPI.Models.LicencaConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApresenFimLucrativos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApresenSemFinsLucrativos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distribuicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExibirEmissoraRadio")
                        .HasColumnType("bit");

                    b.Property<bool>("ExibirEmissoraTV")
                        .HasColumnType("bit");

                    b.Property<Guid>("LicencaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PeriodoUso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Porcentagem")
                        .HasColumnType("int");

                    b.Property<int>("Preco")
                        .HasColumnType("int");

                    b.Property<int>("RoyaltShare")
                        .HasColumnType("int");

                    b.Property<string>("StreamingAudio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreamingVideo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LicencaId");

                    b.ToTable("LicencaConfig");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ApresenFimLucrativos = "300",
                            ApresenSemFinsLucrativos = "2500",
                            Distribuicao = "15000",
                            ExibirEmissoraRadio = true,
                            ExibirEmissoraTV = false,
                            LicencaId = new Guid("724c5c55-ecb3-4fc1-a2ad-d77a02833d24"),
                            PeriodoUso = "1",
                            Porcentagem = 20,
                            Preco = 0,
                            RoyaltShare = 20,
                            StreamingAudio = "20000",
                            StreamingVideo = "20000",
                            Video = "1"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ApresenFimLucrativos = "500",
                            ApresenSemFinsLucrativos = "5000",
                            Distribuicao = "20000",
                            ExibirEmissoraRadio = true,
                            ExibirEmissoraTV = true,
                            LicencaId = new Guid("75974e74-12de-41e4-9fca-f9b87e04e5a6"),
                            PeriodoUso = "3",
                            Porcentagem = 30,
                            Preco = 0,
                            RoyaltShare = 20,
                            StreamingAudio = "50000",
                            StreamingVideo = "50000",
                            Video = "1"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ApresenFimLucrativos = "Ilimitado",
                            ApresenSemFinsLucrativos = "Ilimitado",
                            Distribuicao = "Ilimitado",
                            ExibirEmissoraRadio = true,
                            ExibirEmissoraTV = true,
                            LicencaId = new Guid("ead25d1b-6568-4913-98cd-2f363f235d8b"),
                            PeriodoUso = "Ilimitado",
                            Porcentagem = 100,
                            Preco = 0,
                            RoyaltShare = 20,
                            StreamingAudio = "Ilimitado",
                            StreamingVideo = "Ilimitado",
                            Video = "Ilimitado"
                        });
                });

            modelBuilder.Entity("BeatNationAPI.Models.PresetLicenca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PresetLicencas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("97806a3e-ea4d-4c0f-a82f-664f9016990f"),
                            Descricao = "Preset inicial com as 3 licenças padrão",
                            Nome = "Default"
                        });
                });

            modelBuilder.Entity("BeatNationAPI.Models.BeatColab", b =>
                {
                    b.HasOne("BeatNationAPI.Models.Beat", "Beat")
                        .WithMany("Colaboradores")
                        .HasForeignKey("BeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beat");
                });

            modelBuilder.Entity("BeatNationAPI.Models.BeatLicencas", b =>
                {
                    b.HasOne("BeatNationAPI.Models.Beat", "Beat")
                        .WithMany("BeatLicencas")
                        .HasForeignKey("BeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeatNationAPI.Models.Licenca", "Licencas")
                        .WithMany()
                        .HasForeignKey("LicencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beat");

                    b.Navigation("Licencas");
                });

            modelBuilder.Entity("BeatNationAPI.Models.Licenca", b =>
                {
                    b.HasOne("BeatNationAPI.Models.PresetLicenca", "PresetLicenca")
                        .WithMany("Licencas")
                        .HasForeignKey("PresetLicencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PresetLicenca");
                });

            modelBuilder.Entity("BeatNationAPI.Models.LicencaConfig", b =>
                {
                    b.HasOne("BeatNationAPI.Models.Licenca", "Licenca")
                        .WithMany("LicencaConfig")
                        .HasForeignKey("LicencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licenca");
                });

            modelBuilder.Entity("BeatNationAPI.Models.Beat", b =>
                {
                    b.Navigation("BeatLicencas");

                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("BeatNationAPI.Models.Licenca", b =>
                {
                    b.Navigation("LicencaConfig");
                });

            modelBuilder.Entity("BeatNationAPI.Models.PresetLicenca", b =>
                {
                    b.Navigation("Licencas");
                });
#pragma warning restore 612, 618
        }
    }
}
