// <auto-generated />
using System;
using BeatNationAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeatNationAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeatNationAPI.Models.Beat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Bpm")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Escala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlCapa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlMp3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlTrackout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlWav")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Beats");
                });

            modelBuilder.Entity("BeatNationAPI.Models.BeatColab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Participacao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BeatId");

                    b.ToTable("BeatColabs");
                });

            modelBuilder.Entity("BeatNationAPI.Models.BeatLicencas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LicencaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PresetLicencaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BeatId");

                    b.HasIndex("LicencaId");

                    b.ToTable("BeatLicencas");
                });

            modelBuilder.Entity("BeatNationAPI.Models.LicencaBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LicencasBase");

                    b.HasData(
                        new
                        {
                            Id = new Guid("724c5c55-ecb3-4fc1-a2ad-d77a02833d24"),
                            Nome = "Básica"
                        },
                        new
                        {
                            Id = new Guid("75974e74-12de-41e4-9fca-f9b87e04e5a6"),
                            Nome = "VIP"
                        },
                        new
                        {
                            Id = new Guid("ead25d1b-6568-4913-98cd-2f363f235d8b"),
                            Nome = "Exclusiva"
                        });
                });

            modelBuilder.Entity("BeatNationAPI.Models.PresetLicenca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PresetLicencas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("97806a3e-ea4d-4c0f-a82f-664f9016990f"),
                            Descricao = "Preset inicial com as 3 licenças padrão",
                            Nome = "Default"
                        });
                });

            modelBuilder.Entity("BeatNationAPI.Models.PresetLicencaConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApresenFimLucrativos")
                        .HasColumnType("int");

                    b.Property<int>("ApresenSemFinsLucrativos")
                        .HasColumnType("int");

                    b.Property<int>("Distribuicao")
                        .HasColumnType("int");

                    b.Property<bool>("ExibirEmissoraRadio")
                        .HasColumnType("bit");

                    b.Property<bool>("ExibirEmissoraTV")
                        .HasColumnType("bit");

                    b.Property<Guid>("LicencaBaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PeriodoUso")
                        .HasColumnType("int");

                    b.Property<int>("Porcentagem")
                        .HasColumnType("int");

                    b.Property<int>("Preco")
                        .HasColumnType("int");

                    b.Property<Guid>("PresetLicencaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoyaltShare")
                        .HasColumnType("int");

                    b.Property<int>("StreamingAudio")
                        .HasColumnType("int");

                    b.Property<int>("StreamingVideo")
                        .HasColumnType("int");

                    b.Property<int>("Video")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicencaBaseId");

                    b.HasIndex("PresetLicencaId");

                    b.ToTable("PresetLicencasConfig");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ApresenFimLucrativos = 300,
                            ApresenSemFinsLucrativos = 2500,
                            Distribuicao = 15000,
                            ExibirEmissoraRadio = true,
                            ExibirEmissoraTV = false,
                            LicencaBaseId = new Guid("724c5c55-ecb3-4fc1-a2ad-d77a02833d24"),
                            PeriodoUso = 1,
                            Porcentagem = 20,
                            Preco = 0,
                            PresetLicencaId = new Guid("97806a3e-ea4d-4c0f-a82f-664f9016990f"),
                            RoyaltShare = 20,
                            StreamingAudio = 20000,
                            StreamingVideo = 20000,
                            Video = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ApresenFimLucrativos = 500,
                            ApresenSemFinsLucrativos = 5000,
                            Distribuicao = 20000,
                            ExibirEmissoraRadio = true,
                            ExibirEmissoraTV = true,
                            LicencaBaseId = new Guid("75974e74-12de-41e4-9fca-f9b87e04e5a6"),
                            PeriodoUso = 3,
                            Porcentagem = 30,
                            Preco = 0,
                            PresetLicencaId = new Guid("97806a3e-ea4d-4c0f-a82f-664f9016990f"),
                            RoyaltShare = 20,
                            StreamingAudio = 50000,
                            StreamingVideo = 50000,
                            Video = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ApresenFimLucrativos = 999999,
                            ApresenSemFinsLucrativos = 999999,
                            Distribuicao = 999999,
                            ExibirEmissoraRadio = true,
                            ExibirEmissoraTV = true,
                            LicencaBaseId = new Guid("ead25d1b-6568-4913-98cd-2f363f235d8b"),
                            PeriodoUso = 99999,
                            Porcentagem = 100,
                            Preco = 0,
                            PresetLicencaId = new Guid("97806a3e-ea4d-4c0f-a82f-664f9016990f"),
                            RoyaltShare = 20,
                            StreamingAudio = 999999,
                            StreamingVideo = 999999,
                            Video = 999999
                        });
                });

            modelBuilder.Entity("BeatNationAPI.Models.BeatColab", b =>
                {
                    b.HasOne("BeatNationAPI.Models.Beat", "Beat")
                        .WithMany("Colaboradores")
                        .HasForeignKey("BeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beat");
                });

            modelBuilder.Entity("BeatNationAPI.Models.BeatLicencas", b =>
                {
                    b.HasOne("BeatNationAPI.Models.Beat", "Beat")
                        .WithMany("BeatLicencas")
                        .HasForeignKey("BeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeatNationAPI.Models.LicencaBase", "Licenca")
                        .WithMany()
                        .HasForeignKey("LicencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beat");

                    b.Navigation("Licenca");
                });

            modelBuilder.Entity("BeatNationAPI.Models.PresetLicencaConfig", b =>
                {
                    b.HasOne("BeatNationAPI.Models.LicencaBase", "Licencas")
                        .WithMany("Presets")
                        .HasForeignKey("LicencaBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeatNationAPI.Models.PresetLicenca", "PresetLicenca")
                        .WithMany("Licencas")
                        .HasForeignKey("PresetLicencaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licencas");

                    b.Navigation("PresetLicenca");
                });

            modelBuilder.Entity("BeatNationAPI.Models.Beat", b =>
                {
                    b.Navigation("BeatLicencas");

                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("BeatNationAPI.Models.LicencaBase", b =>
                {
                    b.Navigation("Presets");
                });

            modelBuilder.Entity("BeatNationAPI.Models.PresetLicenca", b =>
                {
                    b.Navigation("Licencas");
                });
#pragma warning restore 612, 618
        }
    }
}
