// <auto-generated />
using System;
using BeatNationAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeatNationAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeatNationAPI.Models.Beat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEM")
                        .HasColumnType("datetime2");

                    b.Property<int>("Bpm")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEM")
                        .HasColumnType("datetime2");

                    b.Property<string>("Escala")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISRC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlCAPA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlMP3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlTRACKOUT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlWAV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Beats");
                });

            modelBuilder.Entity("BeatNationAPI.Models.BeatColab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeatId")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Participacao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BeatId");

                    b.ToTable("BeatColabs");
                });

            modelBuilder.Entity("BeatNationAPI.Models.Licenca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApresenFimLucrativos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApresenSemFinsLucrativos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Distribuicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExibirEmissoraRadio")
                        .HasColumnType("bit");

                    b.Property<bool>("ExibirEmissoraTV")
                        .HasColumnType("bit");

                    b.Property<string>("NomeLicencas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Porcentagem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoyaltShare")
                        .HasColumnType("int");

                    b.Property<string>("StreamingAudio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreamingVideo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Licencas");

                    b.HasDiscriminator().HasValue("Licenca");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BeatNationAPI.Models.LicencaPresets", b =>
                {
                    b.HasBaseType("BeatNationAPI.Models.Licenca");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomePreset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PresetId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("LicencaPresets");
                });

            modelBuilder.Entity("BeatNationAPI.Models.BeatLicencas", b =>
                {
                    b.HasBaseType("BeatNationAPI.Models.LicencaPresets");

                    b.Property<int>("BeatId")
                        .HasColumnType("int");

                    b.HasIndex("BeatId");

                    b.HasDiscriminator().HasValue("BeatLicencas");
                });

            modelBuilder.Entity("BeatNationAPI.Models.BeatColab", b =>
                {
                    b.HasOne("BeatNationAPI.Models.Beat", "Beat")
                        .WithMany("Colaboradores")
                        .HasForeignKey("BeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beat");
                });

            modelBuilder.Entity("BeatNationAPI.Models.BeatLicencas", b =>
                {
                    b.HasOne("BeatNationAPI.Models.Beat", "Beat")
                        .WithMany("Licencas")
                        .HasForeignKey("BeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beat");
                });

            modelBuilder.Entity("BeatNationAPI.Models.Beat", b =>
                {
                    b.Navigation("Colaboradores");

                    b.Navigation("Licencas");
                });
#pragma warning restore 612, 618
        }
    }
}
