
services:
  beatapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beatapi
    environment:
      ConnectionStrings__SQL: "Server=DBBeatnation,1433;Database=master;User Id=sa;Password=Felhada131$;Encrypt=True;TrustServerCertificate=True;"
      DOTNET_ENVIRONMENT: "Development"
    ports:
      - "5000:8080"
    networks:
      - authapi_default
    restart: always


networks:
  authapi_default:
    external: true
